### ISSUE TITLE
Recommend Mods for the Modpack

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/falloutnewvegasmods#6]
Suggest new mods.

**Comment by TDarkShadow** [comment]
I'm surprised you haven't added [Unnecessary Tweaks](https://github.com/maletsna/xSE/releases) and/or [lStewieAl's Tweaks](https://www.nexusmods.com/newvegas/mods/66347).
Arguably 2 of the best yet lightweight mods, even for vanilla play.

**Comment by valkyrienyanko** [comment]
Moving to README.md.
